export enum STATUS {
    INICIAL = "INICIAL",
    CADASTRO_COMPLEMENTAR = "CADASTRO_COMPLEMENTAR",
    CADASTRO_SOCIAL = "CADASTRO_SOCIAL",
    PROVA_LOGICA = "PROVA_LOGICA",
    ENTREVISTA = "ENTREVISTA",
    AGUARDANDO = "AGUARDANDO",
    APROVADO = "APROVADO",
    REPROVADO = "REPROVADO",
  }
  